= Safe food ideas for picky eaters
:toc: 

== Recipes
=== nurp's oatmeal recipe
I make this for my baby since almost every night and she eats it while watching Bobo.

_Ingredients_ +

* 1 tequila glass (60 ml) of steel cut oats
* 2 tequila glass (120 ml) of water
* 2 walnuts (shelled if possible), grind with a mortar and pestle well until you see the fat
* pinch of cinnamon
* splash of milk
* 1/3rd of a banana, mash well with a fork so it tastes sweeter
* (optional) 4-5 dried strawberry powder

Put the oat and water in a pan, cover at medium heat (5 with electric stove). When it starts boiling, simmer on law (1.5 with electric stove) for 10 minutes. It should be a bit thick consistency for a splash of milk later. +
When it's cooked, add a big pinch of cinnamon powder, banana, strawberry powder and walnut paste. Lastly pour a splash of milk to make it taste even milder. Serve warm.

=== fruit bar (riegel, fruchtbar)
_recipe from: https://www.azafran.de/blog/frucht-riegel-rezept.html_ +
_video: https://www.youtube.com/watch?v=gDNGbUPDtDk_

_Ingredients_ +

* 100 g Cashew nuts
* 100 g soft dates (medjool)
* 100 g sun dried apricots (dark ones)
* 3 TBSP strawberry powder (make the powder from about 20 dried strawberries)
* edible papers (oblaten)
* _(optional) schredded coconut_

process cashews
puree apricots and dates
mix strawberry powder, cashews and puree. press between oblaten and cut. keep in fridge.

=== red lentil soup
_recipe from: Vegetarian cooking of the Mediterranean: from Gibraltar to Istanbul (1997) by Cornelia Schinharl page 36. (can be borrowed at onlinelibrary: https://openlibrary.org/books/OL1002510M/Vegetarian_cooking_of_the_Mediterranean)_

I think this is the best red lentil soup!
I don't use as much butter as in the recipe, and I add a bit olive oil. Because, why not.
I also cook carrots and onions until their raw smell goes away (about 20 minutes simmer) and then add the lentils.

_Ingredients_

* 1 large onion
* 2 carrots
* 4 tbsp (60 g) butter
* 200 g (1/2 lb) red lentils
* 1 1/8 l (4 3/4 cups) vegetable stock
* salt
* freshly ground white pepper
* lemon for serving

_follow the library link for instructions_

=== Savory waffles
_recipe from: https://www.healthylittlefoodies.com/savoury-waffles/#recipe_

=== Steamed salmon

If using pressure cook, put minimal amount of water in the pan, put the steam basket onto the pilon. Place baking paper in the steam basket. Place salmon skin side down in it. Put pepper, salt and lemon juice on top. +
Cook in high pressure (setting 2 on fissler) for 6-8 minutes. +
My baby likes it mixed with mayonnaise.

=== Ebly risotto with porcini mushrooms
_recipe from: https://fooby.ch/en/recipes/13853/ebly-risotto-with-porcini-mushrooms?startAuto1=0_

* ½ tbspolive oil
* 1 onion, finely chopped
* 1 garlic clove, thinly sliced
* 20 g dried porcini mushrooms
* 200 g pre-cooked durum wheat (Ebly®)
* 6 dl vegetable bouillon
* 200 g sour single cream
* 50 g grated Sbrinz
* 50 g rocket, roughly chopped
* salt and pepper to taste

follow the link for the recipe

=== Jacques Pepin's American style omelette
_recipe from: https://www.youtube.com/watch?v=s10etP1p2bU_

